USE master;
GO

DROP DATABASE IF EXISTS EventPlanner;

CREATE DATABASE EventPlanner;
GO

USE EventPlanner;
GO

CREATE TABLE Events (
	EventID UNIQUEIDENTIFIER,
	Name NVARCHAR(50),
	Location NVARCHAR(100),
	StartTime DATETIME2,
	EndTime DATETIME2,

	CONSTRAINT PK_Events PRIMARY KEY(EventID)

);

CREATE TABLE Organizers (
	UserName NVARCHAR(50),

	Name NVARCHAR(50),
	Age NVARCHAR(50),

	CONSTRAINT PK_Organizers PRIMARY KEY(UserName)
);

CREATE TABLE Organizes (
	EID UNIQUEIDENTIFIER,
	OID NVARCHAR(50),

	CONSTRAINT PK_Organizes PRIMARY KEY (EID, OID),
	CONSTRAINT FK_Organizes_Organizers FOREIGN KEY (OID) REFERENCES Organizers(UserName),
	CONSTRAINT FK_Organizes_Events FOREIGN KEY (EID) REFERENCES Events(EventID)

);

CREATE TABLE Pictures (
	PictureID UNIQUEIDENTIFIER,
	EID UNIQUEIDENTIFIER,

	OriginalName NVARCHAR(100),
	UploadedBy NVARCHAR(50),
	UploadDate DATETIME2,


	CONSTRAINT PK_Pictures PRIMARY KEY (PictureID),
	CONSTRAINT FK_Pictures_Events FOREIGN KEY (EID) REFERENCES Events(EventID),
	CONSTRAINT FK_Pictures_Organizers FOREIGN KEY (UploadedBy) REFERENCES Organizers(UserName)
);

CREATE TABLE Users (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Username NVARCHAR(100) NOT NULL UNIQUE,
	PasswordHash NVARCHAR(255) NOT NULL,
);